from enum import Enum


class InputEvent(str, Enum):
    BUTTON_F1="BUTTON_F1"; BUTTON_F2="BUTTON_F2"; BUTTON_F3="BUTTON_F3"; BUTTON_F4="BUTTON_F4"
    BUTTON_MENU="BUTTON_MENU"; ENCODER_LEFT="ENCODER_LEFT"; ENCODER_RIGHT="ENCODER_RIGHT"
    ENCODER_PRESS="ENCODER_PRESS"; ENCODER_LONG_PRESS="ENCODER_LONG_PRESS"
